# TCL File Generated by Component Editor 15.1
# Mon Feb 15 16:28:01 CST 2016
# DO NOT MODIFY


# 
# y_enhance_top "y_enhance_top" v1.0
#  2016.02.15.16:28:01
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module y_enhance_top
# 
set_module_property DESCRIPTION ""
set_module_property NAME y_enhance_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME y_enhance_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL y_enhance_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file div16.v VERILOG PATH div16.v
add_fileset_file reg_block.v VERILOG PATH reg_block.v
add_fileset_file y_enhance_calcu.v VERILOG PATH y_enhance_calcu.v
add_fileset_file y_enhance_rate.v VERILOG PATH y_enhance_rate.v
add_fileset_file y_enhance_top.v VERILOG PATH y_enhance_top.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL y_enhance_top
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file div16.v VERILOG PATH div16.v
add_fileset_file reg_block.v VERILOG PATH reg_block.v
add_fileset_file y_enhance_calcu.v VERILOG PATH y_enhance_calcu.v
add_fileset_file y_enhance_rate.v VERILOG PATH y_enhance_rate.v
add_fileset_file y_enhance_top.v VERILOG PATH y_enhance_top.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 slave_addr address Input 4
add_interface_port avalon_slave_0 slave_rd read Input 1
add_interface_port avalon_slave_0 slave_wr write Input 1
add_interface_port avalon_slave_0 slave_wrdata writedata Input 32
add_interface_port avalon_slave_0 slave_rddata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point y_video_in
# 
add_interface y_video_in avalon_streaming end
set_interface_property y_video_in associatedClock clock
set_interface_property y_video_in associatedReset reset_sink
set_interface_property y_video_in dataBitsPerSymbol 8
set_interface_property y_video_in errorDescriptor ""
set_interface_property y_video_in firstSymbolInHighOrderBits true
set_interface_property y_video_in maxChannel 0
set_interface_property y_video_in readyLatency 1
set_interface_property y_video_in ENABLED true
set_interface_property y_video_in EXPORT_OF ""
set_interface_property y_video_in PORT_NAME_MAP ""
set_interface_property y_video_in CMSIS_SVD_VARIABLES ""
set_interface_property y_video_in SVD_ADDRESS_GROUP ""

add_interface_port y_video_in video_y_in_data data Input 24
add_interface_port y_video_in video_y_in_eop endofpacket Input 1
add_interface_port y_video_in video_y_in_ready ready Output 1
add_interface_port y_video_in video_y_in_sop startofpacket Input 1
add_interface_port y_video_in video_y_in_valid valid Input 1


# 
# connection point video_out
# 
add_interface video_out avalon_streaming start
set_interface_property video_out associatedClock clock
set_interface_property video_out associatedReset reset_sink
set_interface_property video_out dataBitsPerSymbol 8
set_interface_property video_out errorDescriptor ""
set_interface_property video_out firstSymbolInHighOrderBits true
set_interface_property video_out maxChannel 0
set_interface_property video_out readyLatency 3
set_interface_property video_out ENABLED true
set_interface_property video_out EXPORT_OF ""
set_interface_property video_out PORT_NAME_MAP ""
set_interface_property video_out CMSIS_SVD_VARIABLES ""
set_interface_property video_out SVD_ADDRESS_GROUP ""

add_interface_port video_out video_out_data data Output 24
add_interface_port video_out video_out_ready ready Input 1
add_interface_port video_out video_out_valid valid Output 1


# 
# connection point control_in
# 
add_interface control_in avalon_streaming end
set_interface_property control_in associatedClock clock
set_interface_property control_in associatedReset reset_sink
set_interface_property control_in dataBitsPerSymbol 36
set_interface_property control_in errorDescriptor ""
set_interface_property control_in firstSymbolInHighOrderBits true
set_interface_property control_in maxChannel 0
set_interface_property control_in readyLatency 0
set_interface_property control_in ENABLED true
set_interface_property control_in EXPORT_OF ""
set_interface_property control_in PORT_NAME_MAP ""
set_interface_property control_in CMSIS_SVD_VARIABLES ""
set_interface_property control_in SVD_ADDRESS_GROUP ""

add_interface_port control_in control_in_data data Input 36
add_interface_port control_in control_in_valid valid Input 1


# 
# connection point control_out
# 
add_interface control_out avalon_streaming start
set_interface_property control_out associatedClock clock
set_interface_property control_out associatedReset reset_sink
set_interface_property control_out dataBitsPerSymbol 36
set_interface_property control_out errorDescriptor ""
set_interface_property control_out firstSymbolInHighOrderBits true
set_interface_property control_out maxChannel 0
set_interface_property control_out readyLatency 0
set_interface_property control_out ENABLED true
set_interface_property control_out EXPORT_OF ""
set_interface_property control_out PORT_NAME_MAP ""
set_interface_property control_out CMSIS_SVD_VARIABLES ""
set_interface_property control_out SVD_ADDRESS_GROUP ""

add_interface_port control_out control_out_data data Output 36
add_interface_port control_out control_out_valid valid Output 1

