# TCL File Generated by Component Editor 15.1
# Wed Feb 24 03:23:31 GMT 2016
# DO NOT MODIFY


# 
# hist_gray "hist_gray" v1.0
#  2016.02.24.03:23:31
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module hist_gray
# 
set_module_property DESCRIPTION ""
set_module_property NAME hist_gray
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME hist_gray
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hist_gray
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hist_gray.v VERILOG PATH hist_gray.v TOP_LEVEL_FILE
add_fileset_file frame_cnt.v VERILOG PATH frame_cnt.v
add_fileset_file hist_regenerate.v VERILOG PATH hist_regenerate.v
add_fileset_file p_collect.v VERILOG PATH p_collect.v
add_fileset_file pro_cdf.v VERILOG PATH pro_cdf.v
add_fileset_file ram_p.v VERILOG PATH ram_p.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL hist_gray
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hist_gray.v VERILOG PATH hist_gray.v
add_fileset_file frame_cnt.v VERILOG PATH frame_cnt.v
add_fileset_file hist_regenerate.v VERILOG PATH hist_regenerate.v
add_fileset_file p_collect.v VERILOG PATH p_collect.v
add_fileset_file pro_cdf.v VERILOG PATH pro_cdf.v
add_fileset_file ram_p.v VERILOG PATH ram_p.v


# 
# parameters
# 
add_parameter BITWIDTH INTEGER 19
set_parameter_property BITWIDTH DEFAULT_VALUE 19
set_parameter_property BITWIDTH DISPLAY_NAME BITWIDTH
set_parameter_property BITWIDTH TYPE INTEGER
set_parameter_property BITWIDTH UNITS None
set_parameter_property BITWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BITWIDTH HDL_PARAMETER true
add_parameter W INTEGER 960
set_parameter_property W DEFAULT_VALUE 960
set_parameter_property W DISPLAY_NAME W
set_parameter_property W TYPE INTEGER
set_parameter_property W UNITS None
set_parameter_property W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property W HDL_PARAMETER true
add_parameter H INTEGER 540
set_parameter_property H DEFAULT_VALUE 540
set_parameter_property H DISPLAY_NAME H
set_parameter_property H TYPE INTEGER
set_parameter_property H UNITS None
set_parameter_property H ALLOWED_RANGES -2147483648:2147483647
set_parameter_property H HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point in0
# 
add_interface in0 avalon_streaming end
set_interface_property in0 associatedClock clock
set_interface_property in0 associatedReset reset_sink
set_interface_property in0 dataBitsPerSymbol 8
set_interface_property in0 errorDescriptor ""
set_interface_property in0 firstSymbolInHighOrderBits true
set_interface_property in0 maxChannel 0
set_interface_property in0 readyLatency 1
set_interface_property in0 ENABLED true
set_interface_property in0 EXPORT_OF ""
set_interface_property in0 PORT_NAME_MAP ""
set_interface_property in0 CMSIS_SVD_VARIABLES ""
set_interface_property in0 SVD_ADDRESS_GROUP ""

add_interface_port in0 asi_in0_data data Input 8
add_interface_port in0 asi_in0_valid valid Input 1
add_interface_port in0 asi_in0_ready ready Output 1


# 
# connection point out0
# 
add_interface out0 avalon_streaming start
set_interface_property out0 associatedClock clock
set_interface_property out0 associatedReset reset_sink
set_interface_property out0 dataBitsPerSymbol 8
set_interface_property out0 errorDescriptor ""
set_interface_property out0 firstSymbolInHighOrderBits true
set_interface_property out0 maxChannel 0
set_interface_property out0 readyLatency 1
set_interface_property out0 ENABLED true
set_interface_property out0 EXPORT_OF ""
set_interface_property out0 PORT_NAME_MAP ""
set_interface_property out0 CMSIS_SVD_VARIABLES ""
set_interface_property out0 SVD_ADDRESS_GROUP ""

add_interface_port out0 aso_out0_ready ready Input 1
add_interface_port out0 aso_out0_data data Output 24
add_interface_port out0 aso_out0_valid valid Output 1


# 
# connection point in1
# 
add_interface in1 avalon_streaming end
set_interface_property in1 associatedClock clock
set_interface_property in1 associatedReset reset_sink
set_interface_property in1 dataBitsPerSymbol 36
set_interface_property in1 errorDescriptor ""
set_interface_property in1 firstSymbolInHighOrderBits true
set_interface_property in1 maxChannel 0
set_interface_property in1 readyLatency 0
set_interface_property in1 ENABLED true
set_interface_property in1 EXPORT_OF ""
set_interface_property in1 PORT_NAME_MAP ""
set_interface_property in1 CMSIS_SVD_VARIABLES ""
set_interface_property in1 SVD_ADDRESS_GROUP ""

add_interface_port in1 asi_in1_data data Input 36
add_interface_port in1 asi_in1_valid valid Input 1


# 
# connection point out1
# 
add_interface out1 avalon_streaming start
set_interface_property out1 associatedClock clock
set_interface_property out1 associatedReset reset_sink
set_interface_property out1 dataBitsPerSymbol 36
set_interface_property out1 errorDescriptor ""
set_interface_property out1 firstSymbolInHighOrderBits true
set_interface_property out1 maxChannel 0
set_interface_property out1 readyLatency 0
set_interface_property out1 ENABLED true
set_interface_property out1 EXPORT_OF ""
set_interface_property out1 PORT_NAME_MAP ""
set_interface_property out1 CMSIS_SVD_VARIABLES ""
set_interface_property out1 SVD_ADDRESS_GROUP ""

add_interface_port out1 aso_out1_data data Output 36
add_interface_port out1 aso_out1_valid valid Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset_sink
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_address address Input 2
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0

