# TCL File Generated by Component Editor 15.1
# Mon Feb 15 14:36:42 CST 2016
# DO NOT MODIFY


# 
# gaussian_filter "gaussian_filter" v1.0
#  2016.02.15.14:36:42
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module gaussian_filter
# 
set_module_property DESCRIPTION ""
set_module_property NAME gaussian_filter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME gaussian_filter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL gaussian_filter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gaussian_filter.v VERILOG PATH gaussian_filter.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL gaussian_filter
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file gaussian_filter.v VERILOG PATH gaussian_filter.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point video_out
# 
add_interface video_out avalon_streaming start
set_interface_property video_out associatedClock clock
set_interface_property video_out associatedReset reset_sink
set_interface_property video_out dataBitsPerSymbol 8
set_interface_property video_out errorDescriptor ""
set_interface_property video_out firstSymbolInHighOrderBits true
set_interface_property video_out maxChannel 0
set_interface_property video_out readyLatency 3
set_interface_property video_out ENABLED true
set_interface_property video_out EXPORT_OF ""
set_interface_property video_out PORT_NAME_MAP ""
set_interface_property video_out CMSIS_SVD_VARIABLES ""
set_interface_property video_out SVD_ADDRESS_GROUP ""

add_interface_port video_out video_out_data data Output 24
add_interface_port video_out video_out_ready ready Input 1
add_interface_port video_out video_out_valid valid Output 1


# 
# connection point video_in
# 
add_interface video_in avalon_streaming end
set_interface_property video_in associatedClock clock
set_interface_property video_in associatedReset reset_sink
set_interface_property video_in dataBitsPerSymbol 8
set_interface_property video_in errorDescriptor ""
set_interface_property video_in firstSymbolInHighOrderBits true
set_interface_property video_in maxChannel 0
set_interface_property video_in readyLatency 1
set_interface_property video_in ENABLED true
set_interface_property video_in EXPORT_OF ""
set_interface_property video_in PORT_NAME_MAP ""
set_interface_property video_in CMSIS_SVD_VARIABLES ""
set_interface_property video_in SVD_ADDRESS_GROUP ""

add_interface_port video_in video_in_data data Input 24
add_interface_port video_in video_in_valid valid Input 1
add_interface_port video_in video_in_ready ready Output 1

