# TCL File Generated by Component Editor 15.1
# Sun Feb 14 20:32:24 CST 2016
# DO NOT MODIFY


# 
# debayerii "debayerii" v1.0
#  2016.02.14.20:32:24
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module debayerii
# 
set_module_property DESCRIPTION ""
set_module_property NAME debayerii
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME debayerii
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL debayerii
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Line_Buffer.v VERILOG PATH Line_Buffer.v
add_fileset_file RAW2RGB.v VERILOG PATH RAW2RGB.v
add_fileset_file debayerii.v VERILOG PATH debayerii.v TOP_LEVEL_FILE
add_fileset_file frame_cnt.v VERILOG PATH frame_cnt.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL debayerii
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Line_Buffer.v VERILOG PATH Line_Buffer.v
add_fileset_file RAW2RGB.v VERILOG PATH RAW2RGB.v
add_fileset_file debayerii.v VERILOG PATH debayerii.v
add_fileset_file frame_cnt.v VERILOG PATH frame_cnt.v


# 
# parameters
# 
add_parameter W INTEGER 1920
set_parameter_property W DEFAULT_VALUE 1920
set_parameter_property W DISPLAY_NAME W
set_parameter_property W TYPE INTEGER
set_parameter_property W UNITS None
set_parameter_property W HDL_PARAMETER true
add_parameter H INTEGER 1080
set_parameter_property H DEFAULT_VALUE 1080
set_parameter_property H DISPLAY_NAME H
set_parameter_property H TYPE INTEGER
set_parameter_property H UNITS None
set_parameter_property H HDL_PARAMETER true
add_parameter DEPTH INTEGER 8
set_parameter_property DEPTH DEFAULT_VALUE 8
set_parameter_property DEPTH DISPLAY_NAME DEPTH
set_parameter_property DEPTH TYPE INTEGER
set_parameter_property DEPTH UNITS None
set_parameter_property DEPTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point video_out
# 
add_interface video_out avalon_streaming start
set_interface_property video_out associatedClock clock
set_interface_property video_out associatedReset reset_sink
set_interface_property video_out dataBitsPerSymbol 8
set_interface_property video_out errorDescriptor ""
set_interface_property video_out firstSymbolInHighOrderBits true
set_interface_property video_out maxChannel 0
set_interface_property video_out readyLatency 1
set_interface_property video_out ENABLED true
set_interface_property video_out EXPORT_OF ""
set_interface_property video_out PORT_NAME_MAP ""
set_interface_property video_out CMSIS_SVD_VARIABLES ""
set_interface_property video_out SVD_ADDRESS_GROUP ""

add_interface_port video_out source_data data Output 24
add_interface_port video_out source_ready ready Input 1
add_interface_port video_out source_valid valid Output 1


# 
# connection point video_in
# 
add_interface video_in avalon_streaming end
set_interface_property video_in associatedClock clock
set_interface_property video_in associatedReset reset_sink
set_interface_property video_in dataBitsPerSymbol 8
set_interface_property video_in errorDescriptor ""
set_interface_property video_in firstSymbolInHighOrderBits true
set_interface_property video_in maxChannel 0
set_interface_property video_in readyLatency 1
set_interface_property video_in ENABLED true
set_interface_property video_in EXPORT_OF ""
set_interface_property video_in PORT_NAME_MAP ""
set_interface_property video_in CMSIS_SVD_VARIABLES ""
set_interface_property video_in SVD_ADDRESS_GROUP ""

add_interface_port video_in sink_data data Input 8
add_interface_port video_in sink_valid valid Input 1
add_interface_port video_in sink_ready ready Output 1


# 
# connection point control_in
# 
add_interface control_in avalon_streaming end
set_interface_property control_in associatedClock clock
set_interface_property control_in associatedReset reset_sink
set_interface_property control_in dataBitsPerSymbol 36
set_interface_property control_in errorDescriptor ""
set_interface_property control_in firstSymbolInHighOrderBits true
set_interface_property control_in maxChannel 0
set_interface_property control_in readyLatency 0
set_interface_property control_in ENABLED true
set_interface_property control_in EXPORT_OF ""
set_interface_property control_in PORT_NAME_MAP ""
set_interface_property control_in CMSIS_SVD_VARIABLES ""
set_interface_property control_in SVD_ADDRESS_GROUP ""

add_interface_port control_in control_in_data data Input 36
add_interface_port control_in control_in_valid valid Input 1


# 
# connection point control_out
# 
add_interface control_out avalon_streaming start
set_interface_property control_out associatedClock clock
set_interface_property control_out associatedReset reset_sink
set_interface_property control_out dataBitsPerSymbol 36
set_interface_property control_out errorDescriptor ""
set_interface_property control_out firstSymbolInHighOrderBits true
set_interface_property control_out maxChannel 0
set_interface_property control_out readyLatency 0
set_interface_property control_out ENABLED true
set_interface_property control_out EXPORT_OF ""
set_interface_property control_out PORT_NAME_MAP ""
set_interface_property control_out CMSIS_SVD_VARIABLES ""
set_interface_property control_out SVD_ADDRESS_GROUP ""

add_interface_port control_out control_out_data data Output 36
add_interface_port control_out control_out_valid valid Output 1

