# TCL File Generated by Component Editor 15.1
# Wed Feb 03 02:24:05 GMT 2016
# DO NOT MODIFY


# 
# pre "pre" v1.0
#  2016.02.03.02:24:05
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module pre
# 
set_module_property DESCRIPTION ""
set_module_property NAME pre
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ip_frame
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pre
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pre
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file control_in.v VERILOG PATH control_in.v
add_fileset_file pre.v VERILOG PATH pre.v TOP_LEVEL_FILE
add_fileset_file video_in.v VERILOG PATH video_in.v
add_fileset_file flow_monitor.v VERILOG PATH flow_monitor.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL pre
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file control_in.v VERILOG PATH control_in.v
add_fileset_file pre.v VERILOG PATH pre.v
add_fileset_file video_in.v VERILOG PATH video_in.v
add_fileset_file flow_monitor.v VERILOG PATH flow_monitor.v


# 
# parameters
# 
add_parameter BITWDITH INTEGER 32
set_parameter_property BITWDITH DEFAULT_VALUE 32
set_parameter_property BITWDITH DISPLAY_NAME BITWDITH
set_parameter_property BITWDITH TYPE INTEGER
set_parameter_property BITWDITH UNITS None
set_parameter_property BITWDITH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BITWDITH HDL_PARAMETER true
add_parameter FIFO_DEPTH INTEGER 16
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 16
set_parameter_property FIFO_DEPTH DISPLAY_NAME FIFO_DEPTH
set_parameter_property FIFO_DEPTH TYPE INTEGER
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_DEPTH HDL_PARAMETER true
add_parameter ALMOST_FULL_DEPTH INTEGER 15
set_parameter_property ALMOST_FULL_DEPTH DEFAULT_VALUE 15
set_parameter_property ALMOST_FULL_DEPTH DISPLAY_NAME ALMOST_FULL_DEPTH
set_parameter_property ALMOST_FULL_DEPTH TYPE INTEGER
set_parameter_property ALMOST_FULL_DEPTH UNITS None
set_parameter_property ALMOST_FULL_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ALMOST_FULL_DEPTH HDL_PARAMETER true
add_parameter DEPTH_WIDTH INTEGER 4
set_parameter_property DEPTH_WIDTH DEFAULT_VALUE 4
set_parameter_property DEPTH_WIDTH DISPLAY_NAME DEPTH_WIDTH
set_parameter_property DEPTH_WIDTH TYPE INTEGER
set_parameter_property DEPTH_WIDTH UNITS None
set_parameter_property DEPTH_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DEPTH_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset_sink
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 1
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink sink_data data Input BITWDITH
add_interface_port avalon_streaming_sink sink_valid valid Input 1
add_interface_port avalon_streaming_sink sink_sop startofpacket Input 1
add_interface_port avalon_streaming_sink sink_eop endofpacket Input 1
add_interface_port avalon_streaming_sink sink_ready ready Output 1


# 
# connection point flow_control
# 
add_interface flow_control conduit end
set_interface_property flow_control associatedClock clock
set_interface_property flow_control associatedReset reset_sink
set_interface_property flow_control ENABLED true
set_interface_property flow_control EXPORT_OF ""
set_interface_property flow_control PORT_NAME_MAP ""
set_interface_property flow_control CMSIS_SVD_VARIABLES ""
set_interface_property flow_control SVD_ADDRESS_GROUP ""

add_interface_port flow_control video_fifo_empty video_fifo_empty Output 1


# 
# connection point control_source
# 
add_interface control_source avalon_streaming start
set_interface_property control_source associatedClock clock
set_interface_property control_source associatedReset reset_sink
set_interface_property control_source dataBitsPerSymbol 36
set_interface_property control_source errorDescriptor ""
set_interface_property control_source firstSymbolInHighOrderBits true
set_interface_property control_source maxChannel 0
set_interface_property control_source readyLatency 0
set_interface_property control_source ENABLED true
set_interface_property control_source EXPORT_OF ""
set_interface_property control_source PORT_NAME_MAP ""
set_interface_property control_source CMSIS_SVD_VARIABLES ""
set_interface_property control_source SVD_ADDRESS_GROUP ""

add_interface_port control_source control_valid valid Output 1
add_interface_port control_source control_data data Output 36


# 
# connection point video_source
# 
add_interface video_source avalon_streaming start
set_interface_property video_source associatedClock clock
set_interface_property video_source associatedReset reset_sink
set_interface_property video_source dataBitsPerSymbol 8
set_interface_property video_source errorDescriptor ""
set_interface_property video_source firstSymbolInHighOrderBits true
set_interface_property video_source maxChannel 0
set_interface_property video_source readyLatency 1
set_interface_property video_source ENABLED true
set_interface_property video_source EXPORT_OF ""
set_interface_property video_source PORT_NAME_MAP ""
set_interface_property video_source CMSIS_SVD_VARIABLES ""
set_interface_property video_source SVD_ADDRESS_GROUP ""

add_interface_port video_source source_video_data data Output BITWDITH
add_interface_port video_source source_video_ready ready Input 1
add_interface_port video_source source_video_valid valid Output 1

