# TCL File Generated by Component Editor 15.1
# Fri Jan 08 09:14:41 MYT 2016
# DO NOT MODIFY


# 
# mipi_csi2 "mipi_csi2" v1.0
#  2016.01.08.09:14:41
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module mipi_csi2
# 
set_module_property DESCRIPTION ""
set_module_property NAME mipi_csi2
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "mipi IP"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mipi_csi2
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL csi2_rx
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file csi2_rx.v VERILOG PATH csi2_rx.v TOP_LEVEL_FILE
add_fileset_file ecc_check.v VERILOG PATH ecc_check.v
add_fileset_file fifo34.v VERILOG PATH fifo34.v
add_fileset_file frame_dat.v VERILOG PATH frame_dat.v
add_fileset_file lane_merging.v VERILOG PATH lane_merging.v
add_fileset_file phase_shift.v VERILOG PATH phase_shift.v
add_fileset_file sync_detect.v VERILOG PATH sync_detect.v
add_fileset_file dat_end_check.v VERILOG PATH dat_end_check.v
add_fileset_file lane_delay.v VERILOG PATH lane_delay.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL csi2_rx
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file csi2_rx.v VERILOG PATH csi2_rx.v
add_fileset_file ecc_check.v VERILOG PATH ecc_check.v
add_fileset_file fifo34.v VERILOG PATH fifo34.v
add_fileset_file frame_dat.v VERILOG PATH frame_dat.v
add_fileset_file lane_merging.v VERILOG PATH lane_merging.v
add_fileset_file phase_shift.v VERILOG PATH phase_shift.v
add_fileset_file sync_detect.v VERILOG PATH sync_detect.v
add_fileset_file dat_end_check.v VERILOG PATH dat_end_check.v
add_fileset_file lane_delay.v VERILOG PATH lane_delay.v


# 
# parameters
# 
add_parameter IDLE STRING IDLE
set_parameter_property IDLE DEFAULT_VALUE IDLE
set_parameter_property IDLE DISPLAY_NAME IDLE
set_parameter_property IDLE TYPE STRING
set_parameter_property IDLE ENABLED false
set_parameter_property IDLE UNITS None
set_parameter_property IDLE HDL_PARAMETER true
add_parameter READ STRING READ
set_parameter_property READ DEFAULT_VALUE READ
set_parameter_property READ DISPLAY_NAME READ
set_parameter_property READ TYPE STRING
set_parameter_property READ ENABLED false
set_parameter_property READ UNITS None
set_parameter_property READ HDL_PARAMETER true
add_parameter FINISH STRING FINISH
set_parameter_property FINISH DEFAULT_VALUE FINISH
set_parameter_property FINISH DISPLAY_NAME FINISH
set_parameter_property FINISH TYPE STRING
set_parameter_property FINISH ENABLED false
set_parameter_property FINISH UNITS None
set_parameter_property FINISH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock st_clk
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 1
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source avl_dat data Output 32
add_interface_port avalon_streaming_source avl_eof endofpacket Output 1
add_interface_port avalon_streaming_source avl_sof startofpacket Output 1
add_interface_port avalon_streaming_source avl_valid valid Output 1
add_interface_port avalon_streaming_source avl_ready ready Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock sysclk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point LP
# 
add_interface LP conduit end
set_interface_property LP associatedClock ""
set_interface_property LP associatedReset ""
set_interface_property LP ENABLED true
set_interface_property LP EXPORT_OF ""
set_interface_property LP PORT_NAME_MAP ""
set_interface_property LP CMSIS_SVD_VARIABLES ""
set_interface_property LP SVD_ADDRESS_GROUP ""

add_interface_port LP LP_dn lp_dn Input 1
add_interface_port LP LP_dp lp_dp Input 1


# 
# connection point cam
# 
add_interface cam conduit end
set_interface_property cam associatedClock ""
set_interface_property cam associatedReset ""
set_interface_property cam ENABLED true
set_interface_property cam EXPORT_OF ""
set_interface_property cam PORT_NAME_MAP ""
set_interface_property cam CMSIS_SVD_VARIABLES ""
set_interface_property cam SVD_ADDRESS_GROUP ""

add_interface_port cam cam_pwron pwron Output 1
add_interface_port cam cam_resetb resetb Output 1


# 
# connection point st_clk
# 
add_interface st_clk clock end
set_interface_property st_clk clockRate 0
set_interface_property st_clk ENABLED true
set_interface_property st_clk EXPORT_OF ""
set_interface_property st_clk PORT_NAME_MAP ""
set_interface_property st_clk CMSIS_SVD_VARIABLES ""
set_interface_property st_clk SVD_ADDRESS_GROUP ""

add_interface_port st_clk rdclk clk Input 1


# 
# connection point sysclk
# 
add_interface sysclk clock end
set_interface_property sysclk clockRate 0
set_interface_property sysclk ENABLED true
set_interface_property sysclk EXPORT_OF ""
set_interface_property sysclk PORT_NAME_MAP ""
set_interface_property sysclk CMSIS_SVD_VARIABLES ""
set_interface_property sysclk SVD_ADDRESS_GROUP ""

add_interface_port sysclk sysclk clk Input 1


# 
# connection point lvds
# 
add_interface lvds conduit end
set_interface_property lvds associatedClock ""
set_interface_property lvds associatedReset ""
set_interface_property lvds ENABLED true
set_interface_property lvds EXPORT_OF ""
set_interface_property lvds PORT_NAME_MAP ""
set_interface_property lvds CMSIS_SVD_VARIABLES ""
set_interface_property lvds SVD_ADDRESS_GROUP ""

add_interface_port lvds lvds_hs_clk lvds_hs_clk Input 1
add_interface_port lvds lvds_hs_dat0 lvds_hs_dat0 Input 1
add_interface_port lvds lvds_hs_dat1 lvds_hs_dat1 Input 1
add_interface_port lvds lvds_hs_dat2 lvds_hs_dat2 Input 1
add_interface_port lvds lvds_hs_dat3 lvds_hs_dat3 Input 1

