# TCL File Generated by Component Editor 15.1
# Thu Dec 03 21:45:58 CST 2015
# DO NOT MODIFY


# 
# raw32to8 "raw32to8" v1.0
#  2015.12.03.21:45:58
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module raw32to8
# 
set_module_property DESCRIPTION ""
set_module_property NAME raw32to8
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "mipi IP"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME raw32to8
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL raw32to8
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file raw32to8.v VERILOG PATH raw32to8.v TOP_LEVEL_FILE
add_fileset_file raw_fifo.v VERILOG PATH raw_fifo.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL raw32to8
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file raw32to8.v VERILOG PATH raw32to8.v
add_fileset_file raw_fifo.v VERILOG PATH raw_fifo.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock source_clk
set_interface_property avalon_streaming_source associatedReset source_reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 1
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source source_data data Output 8
add_interface_port avalon_streaming_source source_eop endofpacket Output 1
add_interface_port avalon_streaming_source source_ready ready Input 1
add_interface_port avalon_streaming_source source_sop startofpacket Output 1
add_interface_port avalon_streaming_source source_valid valid Output 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock sink_clk
set_interface_property avalon_streaming_sink associatedReset sink_reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 1
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink sink_sop startofpacket Input 1
add_interface_port avalon_streaming_sink sink_eop endofpacket Input 1
add_interface_port avalon_streaming_sink sink_valid valid Input 1
add_interface_port avalon_streaming_sink sink_ready ready Output 1
add_interface_port avalon_streaming_sink sink_data data Input 32


# 
# connection point sink_clk
# 
add_interface sink_clk clock end
set_interface_property sink_clk clockRate 0
set_interface_property sink_clk ENABLED true
set_interface_property sink_clk EXPORT_OF ""
set_interface_property sink_clk PORT_NAME_MAP ""
set_interface_property sink_clk CMSIS_SVD_VARIABLES ""
set_interface_property sink_clk SVD_ADDRESS_GROUP ""

add_interface_port sink_clk sink_clk clk Input 1


# 
# connection point source_clk
# 
add_interface source_clk clock end
set_interface_property source_clk clockRate 0
set_interface_property source_clk ENABLED true
set_interface_property source_clk EXPORT_OF ""
set_interface_property source_clk PORT_NAME_MAP ""
set_interface_property source_clk CMSIS_SVD_VARIABLES ""
set_interface_property source_clk SVD_ADDRESS_GROUP ""

add_interface_port source_clk source_clk clk Input 1


# 
# connection point sink_reset
# 
add_interface sink_reset reset end
set_interface_property sink_reset associatedClock sink_clk
set_interface_property sink_reset synchronousEdges DEASSERT
set_interface_property sink_reset ENABLED true
set_interface_property sink_reset EXPORT_OF ""
set_interface_property sink_reset PORT_NAME_MAP ""
set_interface_property sink_reset CMSIS_SVD_VARIABLES ""
set_interface_property sink_reset SVD_ADDRESS_GROUP ""

add_interface_port sink_reset sink_rst reset Input 1


# 
# connection point source_reset
# 
add_interface source_reset reset end
set_interface_property source_reset associatedClock sink_clk
set_interface_property source_reset synchronousEdges DEASSERT
set_interface_property source_reset ENABLED true
set_interface_property source_reset EXPORT_OF ""
set_interface_property source_reset PORT_NAME_MAP ""
set_interface_property source_reset CMSIS_SVD_VARIABLES ""
set_interface_property source_reset SVD_ADDRESS_GROUP ""

add_interface_port source_reset source_rst reset Input 1

